### ISSUE TITLE
Unable to start/stop docker pods using Dockman on Apple/ios

### ISSUE THREAD

**Issue by FlyingHavoc** [laurensk/Dockmon#2]
Using Dockmon (Apple; ios 14.6) I can see the list of running or stopped docker pods.
But there is no option to start or stop any of them.

Is this planned for future releases?

Thanks.

**Comment by laurensk** [comment]
Hey @FlyingHavoc,

thanks for reaching out to me. Indeed, for now, it's not possible to start or stop containers from within this app.
As this feature is highly demanded, I will integrate it in Dockmon, but I can't say when...

I hope I could clear up!
Laurens
