### ISSUE TITLE
Show container logs

### ISSUE THREAD

**Issue by smhex** [laurensk/Dockmon#7]
Hi, is it possible to add some more features? My main use case (besides monitoring the container's state) is checking the logs. Swiping left or right on a specific container would be a good entry point to add more functions.

What do you think?

**Comment by laurensk** [comment]
Hi, I do not longer actively maintain this app. Due to my time restrictions, I can't implement any new features into the app. I will leave the issue open, so it could be implemented by others or in the future!

**Comment by smhex** [comment]
I am not an expert for iOS apps, however it might be a good starting point to improve my programming skills 😀. 

I will create a fork as a first step an try to compile it into an app.

What's the kind of license you publish your code?

**Comment by laurensk** [comment]
It's actually a React Native app, so it cross-compiles on iOS and Android!

I will add a license immediately, please give me a minute!

I'm looking forward to seeing your fork and merging it in here!

**Comment by laurensk** [comment]
The license is up!

**Comment by smhex** [comment]
Thank you very much... and don't hurry, my spare time is also limited 😂

**Comment by laurensk** [comment]
We share the same problem 😂
